<img style="float: left; margin: 30px 15px 15px 15px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzQj91sOlkeDFkg5HDbjtR4QJYmLXkfMNig&usqp=CAU" width="400" height="500" /> 
    
    
### <font color='navy'> Simulación matemática. 

**Nombres:** TALPA DE JESUS ORNELAS GÜITRON.

**Fecha:** 05 de septiembre del 2023.

**Expediente** : 745134.
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/TalpaOrnelas/Tarea3_TJOrnelas

# Tarea 2: Clase 5

## Tarea 

### 8.1. Otro problema de transporte

La empresa Carbones de oriente debe ingresar a la empresa un requerimiento mínimo diario de carbón de $5000$ kg de carbón de alto volátil, $4000$ kg de medio volátil y $3000$ kg de bajo volátil para su debido proceso y trasformación. 

La entrada de estos se da en la siguiente tabla (los valores corresponden a un viaje en kg): 

-|Alto volátil|Medio volátil|Bajo volátil
:----|----|----|----
Mina sur|80|70|65
Mina norte|60|50|40
Mina central|40|30|20

El costo del trasporte de un viaje de cada mina es de 2500 dólares, 1500 dólares y 900 dólares, respectivamente. ¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte? 

Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa Carbones de oriente y resolverlo con `linprog`

In [14]:
# Importar numpy para crear las matrices
import scipy.optimize as opt
import numpy as np

In [15]:
# Crear las matrices para resolver el problema
c = np.array([0.6, 0.2])
b = np.array([-25,-6,-30])
A = np.array([[-0.3,-0.05],
             [-0.01,-0.07],
             [-0.1,-0.1]])

In [16]:
c,b,A

(array([0.6, 0.2]),
 array([-25,  -6, -30]),
 array([[-0.3 , -0.05],
        [-0.01, -0.07],
        [-0.1 , -0.1 ]]))

In [17]:
# Resolver utilizando linprog
sol_farma = opt.linprog(c, A_ub=A, b_ub=b)

In [12]:
# Mostrar el resultado
sol_farma

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 76.0
              x: [ 4.000e+01  2.600e+02]
            nit: 2
          lower:  residual: [ 4.000e+01  2.600e+02]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.260e+01  0.000e+00]
                 marginals: [-1.600e+00 -0.000e+00 -1.200e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

### Respuesta planteada en el ejercicio usando (markdown)
 La respuesta es .........

In [13]:
# Extraer el vector solución
x = sol_farma.x
x

array([ 40., 260.])

### 8.2. 
Una empresa de muebles rústicos fabrica entre muchos otros productos cinco tipos de sillas A, B, C, D Y E, las cuales se venden a precio de $1100$, $1300$, $1200$, $980$ y $1010$ pesos cada una y respectivamente. 

Las sillas pasan por cinco procesos: corte, ensamblado, lijado, pintado y sellado, para lo cual se dispone máximo de $17$, $11$, $15$, $12$ y $14$ horas respectivamente a la semana para dedicar a estas operaciones a estos productos.

Los requerimientos, en horas, para cada una de las sillas está dado en la siguiente tabla:

-|Corte|Ensamblado|Lijado|Pintado|Sellado
:----|----|----|----|----|----
Silla A|3|1|3|1|1
Silla B|2|3|2|2|3
Silla C|5|2|2|3|1
Silla D|2|4|1|1|2
Silla E|1|0|2|2|3

¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

Para simplificar la notación use las siguientes variables: 

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E


El objetivo consiste consiste en plantear el problemade programación lineal que permita satisfacer los requerimientos de la empresa empresa de muebles y resolverlo con `linprog`.